apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysite-deployment
  namespace: mysite
spec:
  replicas: 2
  #nodeName: worker-node-1
  selector:
    matchLabels:
      app: mysite
  template:
    metadata:
      labels:
        app: mysite
    spec:
      containers:
      - name: mysite
        image: pavlmark/mysite:v3      # or image local location(?)
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: mysite-service
  namespace: mysite
spec:
  type: NodePort
  selector:
    app: mysite
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30010   # Any free port in 30000-32767
